version: '3.8'

services:
  db:
      container_name: db
      image: fegrus/quiz-db
      ports:
        - "3000:3306"
      environment:
        "MYSQL_DB": "myquizappdb"
        "MYSQL_USER": "user"
        "MYSQL_PASSWORD": "password"
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        apisix:

  sb-server:
    container_name: sb-server
    image: fegrus/quiz-sb-server
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      "DB_URL": "db"
      "MYSQL_DB": "myquizappdb"
      "MYSQL_USER": "user"
      "MYSQL_PASSWORD": "password"
    networks:
      apisix:
    profiles: [sb-server, all]

  score-service:
    image: fegrus/scoreservice
    restart: on-failure
    ports:
      - "8090:8090"
    networks:
      apisix:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "8080:8080"
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: db_keycloak
      KC_DB_URL_DATABASE: keycloak
      #KC_DB: keycloak_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_HOSTNAME: myquizapp-keycloak-auth
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - db_keycloak
    command:
      - start-dev
    networks:
      apisix:

  db_keycloak:
    container_name: db_keycloak
    image: mysql:8.4.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - type: bind
        source: ./mysql_keycloak
        target: /var/lib/mysql
    networks:
      apisix:

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.12.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

volumes:
  mysql:
  apisix_conf:
  mysql_keycloak:
networks:
  apisix:
    driver: bridge
