version: '3.8'

services:
  db:
      container_name: db
      image: fegrus/quiz-db
      ports:
        - "3306:3306"
      environment:
        "MYSQL_DB": "myquizappdb"
        "MYSQL_USER": "user"
        "MYSQL_PASSWORD": "password"
      volumes:
        - ./mysql:/var/lib/mysql
  sb-server:
    container_name: sb-server
    image: fegrus/quiz-sb-server
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      "DB_URL": "db:3306"
      "MYSQL_DB": "myquizappdb"
      "MYSQL_USER": "user"
      "MYSQL_PASSWORD": "password"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sb-server.rule=Host(`localhost`)"
      - "traefik.http.routers.sb-server.entrypoints=web"
    profiles: [sb-server, all]
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:443"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    profiles: [traefik, all]

volumes:
  mysql:
networks:
  mynetwork:
    driver: bridge

