version: '3.8'

services:
  db:
      container_name: db
      image: fegrus/quiz-db
      platform: linux/amd64
      ports:
        - "3306:3306"
      environment:
        "MYSQL_DB": "myquizappdb"
        "MYSQL_USER": "user"
        "MYSQL_PASSWORD": "password"
      volumes:
        - ./mysql:/var/lib/mysql
  sb-server:
    container_name: sb-server
    image: fegrus/quiz-sb-server:0.1.2
    platform: linux/amd64
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      "DB_URL": "db:3306"
      "MYSQL_DB": "myquizappdb"
      "MYSQL_USER": "user"
      "MYSQL_PASSWORD": "password"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sb-server.rule=Host(`localhost`)"
      - "traefik.http.routers.sb-server.entrypoints=web-secure"
      - "traefik.http.routers.sb-server.tls=true"
      #- "traefik.http.middlewares.test-auth.forwardauth.address=https://example.com/auth"
    profiles: [sb-server, all]
  db_keycloak:
    container_name: db_keycloak
    image: mysql:8.4.0
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DB: "keycloak_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./mysql_keycloak:/var/lib/mysql
  traefik:
    image: traefik:v3.0
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    profiles: [traefik, all]
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "8081:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db_keycloak:3307
      DB_SCHEMA: public
      DB_DATABASE: keycloak_db
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_HOSTNAME: myquizapp-keycloak-auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    depends_on:
      - db_keycloak
volumes:
  mysql:
networks:
  mynetwork:
    driver: bridge

