
CREATE TABLE `answer` (
                          `_id` int(11) NOT NULL AUTO_INCREMENT,
                          `question_id` int(11) NOT NULL,
                          `answer_text` text NOT NULL,
                          `correct` tinyint(1) NOT NULL,
                          PRIMARY KEY (`_id`),
                          FOREIGN KEY (`question_id`) REFERENCES question(`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `answer` (`question_id`, `answer_text`, `correct`) VALUES
                                                                          (1, '1066', 1),
                                                                          (1, '1939', 0),
                                                                          (1, '45', 0),
                                                                          (1, '1010', 0),
                                                                          (2, '6', 1),
                                                                          (2, '0', 0),
                                                                          (2, '64', 0),
                                                                          (2, '8', 0),
                                                                          (3, '1 0r 0', 1),
                                                                          (3, 'Only 7', 0),
                                                                          (3, 'Anything from one to 10', 0),
                                                                          (3, 'No value at all', 0),
                                                                          (4, '4', 1),
                                                                          (4, 'A half', 0),
                                                                          (4, '7', 0),
                                                                          (4, '64', 0),
                                                                          (5, '8', 1),
                                                                          (5, '64', 0),
                                                                          (5, '128', 0),
                                                                          (5, '1024', 0),
                                                                          (6, '255', 1),
                                                                          (6, '10000000', 0),
                                                                          (6, '42', 0),
                                                                          (6, '256', 0),
                                                                          (7, '1 KiloByte', 1),
                                                                          (7, '1 GigaByte', 0),
                                                                          (7, '4 KiloBytes', 0),
                                                                          (7, '1 Elephant', 0),
                                                                          (8, 'London', 0),
                                                                          (8, 'Berlin', 0),
                                                                          (8, 'Paris', 1),
                                                                          (8, 'Rome', 0),
                                                                          (9, 'Leonardo da Vinci', 1),
                                                                          (9, 'Vincent van Gogh', 0),
                                                                          (9, 'Pablo Picasso', 0),
                                                                          (9, 'Michelangelo', 0),
                                                                          (10, 'Venus', 0),
                                                                          (10, 'Mars', 1),
                                                                          (10, 'Jupiter', 0),
                                                                          (10, 'Saturn', 0),
                                                                          (11, 'H2O', 1),
                                                                          (11, 'CO2', 0),
                                                                          (11, 'O2', 0),
                                                                          (11, 'N2', 0),
                                                                          (12, 'William Shakespeare', 1),
                                                                          (12, 'Jane Austen', 0),
                                                                          (12, 'Charles Dickens', 0),
                                                                          (12, 'Mark Twain', 0),
                                                                          (13, 'Roman Empire', 0),
                                                                          (13, 'Ancient Greece', 0),
                                                                          (13, 'Ancient Egypt', 1),
                                                                          (13, 'Mayan Civilization', 0),
                                                                          (14, 'Athens', 0),
                                                                          (14, 'Rome', 0),
                                                                          (14, 'Florence', 1),
                                                                          (14, 'Paris', 0),
                                                                          (15, 'Thomas Jefferson', 0),
                                                                          (15, 'George Washington', 1),
                                                                          (15, 'Benjamin Franklin', 0),
                                                                          (15, 'John Adams', 0),
                                                                          (16, '1945', 1),
                                                                          (16, '1918', 0),
                                                                          (16, '1939', 0),
                                                                          (16, '1950', 0),
                                                                          (17, 'United States', 0),
                                                                          (17, 'Germany', 0),
                                                                          (17, 'United Kingdom', 1),
                                                                          (17, 'France', 0),
                                                                          (18, 'Au', 1),
                                                                          (18, 'Ag', 0),
                                                                          (18, 'Go', 0),
                                                                          (18, 'Gd', 0),
                                                                          (19, 'Oxygen', 0),
                                                                          (19, 'Carbon dioxide', 1),
                                                                          (19, 'Nitrogen', 0),
                                                                          (19, 'Hydrogen', 0),
                                                                          (20, 'Heart', 0),
                                                                          (20, 'Liver', 1),
                                                                          (20, 'Brain', 0),
                                                                          (20, 'Skin', 0),
                                                                          (21, 'Venus', 0),
                                                                          (21, 'Mercury', 1),
                                                                          (21, 'Mars', 0),
                                                                          (21, 'Jupiter', 0),
                                                                          (22, 'Gravitational pull of the Moon and the Sun', 1),
                                                                          (22, 'Earth''s rotation', 0),
                                                                          (22, 'Earth''s magnetic field', 0),
                                                                          (22, 'Solar flares', 0),
                                                                          (23, 'Pride and Prejudice', 0),
                                                                          (23, 'Wuthering Heights', 0),
                                                                          (23, 'A Tale of Two Cities', 1),
                                                                          (23, 'Jane Eyre', 0),
                                                                          (24, 'William Shakespeare', 1),
                                                                          (24, 'Oscar Wilde', 0),
                                                                          (24, 'George Bernard Shaw', 0),
                                                                          (24, 'Tennessee Williams', 0),
                                                                          (25, 'Mark Twain', 0),
                                                                          (25, 'J.K. Rowling', 0),
                                                                          (25, 'Harper Lee', 1),
                                                                          (25, 'Charles Dickens', 0),
                                                                          (26, 'Little Women', 0),
                                                                          (26, 'Anne of Green Gables', 1),
                                                                          (26, 'Emma', 0),
                                                                          (26, 'Oliver Twist', 0),
                                                                          (27, 'Frodo Baggins', 0),
                                                                          (27, 'Gandalf', 0),
                                                                          (27, 'Sauron', 1),
                                                                          (27, 'Legolas', 0),
                                                                          (28, 'Hyperlinks and Text Markup Language', 0),
                                                                          (28, 'Hyper Text Markup Language', 1),
                                                                          (28, 'Home Tool Markup Language', 0),
                                                                          (28, 'Hyper Text Modern Language', 0),
                                                                          (29, 'Samsung', 0),
                                                                          (29, 'Apple', 1),
                                                                          (29, 'Sony', 0),
                                                                          (29, 'Microsoft', 0),
                                                                          (30, 'Sound processing', 0),
                                                                          (30, 'Graphics rendering', 0),
                                                                          (30, 'Data storage', 1),
                                                                          (30, 'Internet connectivity', 0),
                                                                          (31, 'Java', 0),
                                                                          (31, 'C++', 0),
                                                                          (31, 'Python', 1),
                                                                          (31, 'Ruby', 0),
                                                                          (32, 'Universal Resource Locator', 1),
                                                                          (32, 'Universal Routing Link', 0),
                                                                          (32, 'Unified Resource Listing', 0),
                                                                          (32, 'Underlying Routing Language', 0),
                                                                          (33, 'Canberra', 1),
                                                                          (33, 'Sydney', 0),
                                                                          (33, 'Melbourne', 0),
                                                                          (33, 'Auckland', 0),
                                                                          (34, 'Amazon River', 0),
                                                                          (34, 'Yangtze River', 0),
                                                                          (34, 'Nile River', 1),
                                                                          (34, 'Mississippi River', 0),
                                                                          (35, 'China', 0),
                                                                          (35, 'Japan', 1),
                                                                          (35, 'South Korea', 0),
                                                                          (35, 'Vietnam', 0),
                                                                          (36, 'Africa', 1),
                                                                          (36, 'South America', 0),
                                                                          (36, 'Asia', 0),
                                                                          (36, 'Australia', 0),
                                                                          (37, 'Atlantic Ocean', 0),
                                                                          (37, 'Arctic Ocean', 0),
                                                                          (37, 'Indian Ocean', 0),
                                                                          (37, 'Pacific Ocean', 1),
                                                                          (38, 'Himalayas', 1),
                                                                          (38, 'Rocky Mountains', 0),
                                                                          (38, 'Andes', 0),
                                                                          (38, 'Alps', 0),
                                                                          (39, 'Peru', 1),
                                                                          (39, 'Brazil', 0),
                                                                          (39, 'Mexico', 0),
                                                                          (39, 'Egypt', 0),
                                                                          (40, 'Uganda', 1),
                                                                          (40, 'Kenya', 0),
                                                                          (40, 'Tanzania', 0),
                                                                          (40, 'Nigeria', 0),
                                                                          (41, 'Istanbul', 1),
                                                                          (41, 'Rome', 0),
                                                                          (41, 'Athens', 0),
                                                                          (41, 'Cairo', 0),
                                                                          (42, 'Angel Falls', 1),
                                                                          (42, 'Niagara Falls', 0),
                                                                          (42, 'Iguazu Falls', 0),
                                                                          (42, 'Victoria Falls', 0),
                                                                          (43, 'Canada and Russia', 1),
                                                                          (43, 'United States and Canada', 0),
                                                                          (43, 'India and China', 0),
                                                                          (43, 'Russia and Kazakhstan', 0),
                                                                          (44, 'Rome', 1),
                                                                          (44, 'Paris', 0),
                                                                          (44, 'Athens', 0),
                                                                          (44, 'Berlin', 0),
                                                                          (45, 'Thailand', 1),
                                                                          (45, 'Indonesia', 0),
                                                                          (45, 'Vietnam', 0),
                                                                          (45, 'Malaysia', 0),
                                                                          (46, 'Mediterranean Sea', 1),
                                                                          (46, 'Caribbean Sea', 0),
                                                                          (46, 'Red Sea', 0),
                                                                          (46, 'Arabian Sea', 0),
                                                                          (47, 'Vatican City', 1),
                                                                          (47, 'Monaco', 0),
                                                                          (47, 'Nauru', 0),
                                                                          (47, 'San Marino', 0),
                                                                          (48, 'Basketball', 1),
                                                                          (48, 'Soccer', 0),
                                                                          (48, 'Volleyball', 0),
                                                                          (48, 'Tennis', 0),
                                                                          (49, 'Uruguay', 1),
                                                                          (49, 'Brazil', 0),
                                                                          (49, 'Germany', 0),
                                                                          (49, 'Italy', 0),
                                                                          (50, '300', 0),
                                                                          (50, '200', 0),
                                                                          (50, '100', 0),
                                                                          (50, '300', 1),
                                                                          (51, 'Badminton', 1),
                                                                          (51, 'Table Tennis', 0),
                                                                          (51, 'Squash', 0),
                                                                          (51, 'Tennis', 0),
                                                                          (52, 'Michael Phelps', 1),
                                                                          (52, 'Usain Bolt', 0),
                                                                          (52, 'Carl Lewis', 0),
                                                                          (52, 'Nadia Comăneci', 0),
                                                                          (53, 'Roger Federer', 0),
                                                                          (53, 'Serena Williams', 1),
                                                                          (53, 'Rafael Nadal', 0),
                                                                          (53, 'Steffi Graf', 0),
                                                                          (54, 'England', 1),
                                                                          (54, 'India', 0),
                                                                          (54, 'Australia', 0),
                                                                          (54, 'United States', 0),
                                                                          (55, 'Skiing', 1),
                                                                          (55, 'Snowboarding', 0),
                                                                          (55, 'Cycling', 0),
                                                                          (55, 'Windsurfing', 0),
                                                                          (56, 'Mike Tyson', 1),
                                                                          (56, 'Muhammad Ali', 0),
                                                                          (56, 'Floyd Mayweather Jr.', 0),
                                                                          (56, 'Evander Holyfield', 0),
                                                                          (57, 'Kentucky Derby', 1),
                                                                          (57, 'Preakness Stakes', 0),
                                                                          (57, 'Belmont Stakes', 0),
                                                                          (57, 'Melbourne Cup', 0),
                                                                          (58, 'Shot Put', 1),
                                                                          (58, 'Discus Throw', 0),
                                                                          (58, 'Javelin Throw', 0),
                                                                          (58, 'Hammer Throw', 0),
                                                                          (59, 'Sailing', 1),
                                                                          (59, 'Surfing', 0),
                                                                          (59, 'Ice Hockey', 0),
                                                                          (59, 'Motocross', 0),
                                                                          (60, 'The Masters', 1),
                                                                          (60, 'The Open Championship (British Open)', 0),
                                                                          (60, 'U.S. Open', 0),
                                                                          (60, 'PGA Championship', 0),
                                                                          (61, 'Muhammad Ali', 0),
                                                                          (61, 'Michael Jordan', 1),
                                                                          (61, 'Serena Williams', 0),
                                                                          (61, 'Pele', 0),
                                                                          (62, 'Basketball', 0),
                                                                          (62, 'Football (Soccer)', 0),
                                                                          (62, 'Tennis', 0),
                                                                          (62, 'Basketball', 1),
                                                                          (63, 'Madonna', 1),
                                                                          (63, 'Beyoncé', 0),
                                                                          (63, 'Lady Gaga', 0),
                                                                          (63, 'Adele', 0),
                                                                          (64, 'The Beatles', 1),
                                                                          (64, 'The Rolling Stones', 0),
                                                                          (64, 'Led Zeppelin', 0),
                                                                          (64, 'Queen', 0),
                                                                          (65, 'Piano', 1),
                                                                          (65, 'Guitar', 0),
                                                                          (65, 'Violin', 0),
                                                                          (65, 'Trumpet', 0),
                                                                          (66, 'Ludwig van Beethoven', 1),
                                                                          (66, 'Wolfgang Amadeus Mozart', 0),
                                                                          (66, 'Johann Sebastian Bach', 0),
                                                                          (66, 'Franz Schubert', 0),
                                                                          (67, 'Italy', 1),
                                                                          (67, 'Germany', 0),
                                                                          (67, 'France', 0),
                                                                          (67, 'Spain', 0),
                                                                          (68, 'Michael Jackson', 1),
                                                                          (68, 'Prince', 0),
                                                                          (68, 'Whitney Houston', 0),
                                                                          (68, 'David Bowie', 0),
                                                                          (69, 'Hip Hop', 0),
                                                                          (69, 'Jazz', 0),
                                                                          (69, 'Electronic', 1),
                                                                          (69, 'Classical', 0),
                                                                          (70, 'The Rolling Stones', 0),
                                                                          (70, 'The Who', 0),
                                                                          (70, 'Pink Floyd', 0),
                                                                          (70, 'The Rolling Stones', 1),
                                                                          (71, 'Shamisen', 0),
                                                                          (71, 'Sitar', 0),
                                                                          (71, 'Koto', 1),
                                                                          (71, 'Balalaika', 0),
                                                                          (72, 'Ludwig van Beethoven', 0),
                                                                          (72, 'Wolfgang Amadeus Mozart', 0),
                                                                          (72, 'Johann Sebastian Bach', 0),
                                                                          (72, 'Ludwig van Beethoven', 1),
                                                                          (73, 'Madonna', 1),
                                                                          (73, 'Whitney Houston', 0),
                                                                          (73, 'Britney Spears', 0),
                                                                          (73, 'Celine Dion', 0),
                                                                          (74, 'Tenor', 0),
                                                                          (74, 'Soprano', 0),
                                                                          (74, 'Baritone', 0),
                                                                          (74, 'Countertenor', 1),
                                                                          (75, 'Imagine', 1),
                                                                          (75, 'Hey Jude', 0),
                                                                          (75, 'Bohemian Rhapsody', 0),
                                                                          (75, 'Like a Rolling Stone', 0),
                                                                          (76, 'Johnny Cash', 1),
                                                                          (76, 'Willie Nelson', 0),
                                                                          (76, 'Hank Williams', 0),
                                                                          (76, 'Merle Haggard', 0),
                                                                          (77, '1970s', 1),
                                                                          (77, '1980s', 0),
                                                                          (77, '1960s', 0),
                                                                          (77, '1990s', 0),
                                                                          (78, 'Francis Ford Coppola', 1),
                                                                          (78, 'Martin Scorsese', 0),
                                                                          (78, 'Steven Spielberg', 0),
                                                                          (78, 'Quentin Tarantino', 0),
                                                                          (79, 'Titanic', 1),
                                                                          (79, 'The Notebook', 0),
                                                                          (79, 'Gone with the Wind', 0),
                                                                          (79, 'Casablanca', 0),
                                                                          (80, 'Avengers: Endgame', 1),
                                                                          (80, 'Avatar', 0),
                                                                          (80, 'Titanic', 0),
                                                                          (80, 'Star Wars: The Force Awakens', 0),
                                                                          (81, 'Pierce Brosnan', 1),
                                                                          (81, 'Sean Connery', 0),
                                                                          (81, 'Daniel Craig', 0),
                                                                          (81, 'Roger Moore', 0),
                                                                          (82, 'Tim Robbins', 1),
                                                                          (82, 'Morgan Freeman', 0),
                                                                          (82, 'Tom Hanks', 0),
                                                                          (82, 'Leonardo DiCaprio', 0),
                                                                          (83, 'Frozen', 1),
                                                                          (83, 'Beauty and the Beast', 0),
                                                                          (83, 'Aladdin', 0),
                                                                          (83, 'The Lion King', 0),
                                                                          (84, 'Black Panther', 1),
                                                                          (84, 'The Lion King', 0),
                                                                          (84, 'Avatar', 0),
                                                                          (84, 'Inception', 0),
                                                                          (85, 'Emma Stone', 1),
                                                                          (85, 'Natalie Portman', 0),
                                                                          (85, 'Jennifer Lawrence', 0),
                                                                          (85, 'Meryl Streep', 0),
                                                                          (86, 'The Matrix', 1),
                                                                          (86, 'Blade Runner', 0),
                                                                          (86, 'Star Wars: A New Hope', 0),
                                                                          (86, 'Inception', 0),
                                                                          (87, 'The Silence of the Lambs', 1),
                                                                          (87, 'Se7en', 0),
                                                                          (87, 'Psycho', 0),
                                                                          (87, 'The Sixth Sense', 0),
                                                                          (88, 'A Few Good Men', 1),
                                                                          (88, 'Forrest Gump', 0),
                                                                          (88, 'The Shawshank Redemption', 0),
                                                                          (88, 'The Godfather', 0),
                                                                          (89, 'Hogwarts School of Witchcraft and Wizardry', 1),
                                                                          (89, 'Beauxbatons Academy of Magic', 0),
                                                                          (89, 'Durmstrang Institute', 0),
                                                                          (89, 'Ilvermorny School of Witchcraft and Wizardry', 0),
                                                                          (90, 'Nomadland', 1),
                                                                          (90, 'The Trial of the Chicago 7', 0),
                                                                          (90, 'Mank', 0),
                                                                          (90, 'Minari', 0),
                                                                          (91, 'A box of chocolates', 1),
                                                                          (91, 'A feather', 0),
                                                                          (91, 'A letter from Jenny', 0),
                                                                          (91, 'A ping pong paddle', 0),
                                                                          (92, 'Stand by Me', 1),
                                                                          (92, 'The Goonies', 0),
                                                                          (92, 'Superbad', 0),
                                                                          (92, 'The Breakfast Club', 0),
                                                                          (93, 'Princess Leia', 1),
                                                                          (93, 'Padmé Amidala', 0),
                                                                          (93, 'Rey', 0),
                                                                          (93, 'Mara Jade', 0),
                                                                          (94, 'Vulcans', 1),
                                                                          (94, 'Klingons', 0),
                                                                          (94, 'Wookiees', 0),
                                                                          (94, 'Cybermen', 0),
                                                                          (95, 'Ray Bradbury', 1),
                                                                          (95, 'George Orwell', 0),
                                                                          (95, 'Aldous Huxley', 0),
                                                                          (95, 'Isaac Asimov', 0),
                                                                          (96, 'Discovery One', 0),
                                                                          (96, 'Nostromo', 1),
                                                                          (96, 'Serenity', 0),
                                                                          (96, 'Millennium Falcon', 0),
                                                                          (97, '42', 1),
                                                                          (97, '24', 0),
                                                                          (97, '137', 0),
                                                                          (97, '101', 0),
                                                                          (98, 'Doctor Who', 1),
                                                                          (98, 'Stargate SG-1', 0),
                                                                          (98, 'The X-Files', 0),
                                                                          (98, 'Quantum Leap', 0),
                                                                          (99, 'Blade Runner', 1),
                                                                          (99, 'The Terminator', 0),
                                                                          (99, 'Minority Report', 0),
                                                                          (99, 'A.I. Artificial Intelligence', 0),
                                                                          (100, 'Gort', 1),
                                                                          (100, 'Robby the Robot', 0),
                                                                          (100, 'C-3PO', 0),
                                                                          (100, 'HAL 9000', 0),
                                                                          (101, 'Doctor Who', 0),
                                                                          (101, 'Star Trek', 1),
                                                                          (101, 'The X-Files', 0),
                                                                          (101, 'Battlestar Galactica', 0),
                                                                          (102, 'Blade Runner', 1),
                                                                          (102, 'The Matrix', 0),
                                                                          (102, 'Minority Report', 0),
                                                                          (102, 'The Fifth Element', 0),
                                                                          (103, 'Isaac Asimov', 1),
                                                                          (103, 'Philip K. Dick', 0),
                                                                          (103, 'Arthur C. Clarke', 0),
                                                                          (103, 'Frank Herbert', 0),
                                                                          (104, 'Blue', 0),
                                                                          (104, 'Red', 1),
                                                                          (104, 'Green', 0),
                                                                          (104, 'Yellow', 0),
                                                                          (105, 'Alien', 1),
                                                                          (105, 'Star Wars', 0),
                                                                          (105, 'The Terminator', 0),
                                                                          (105, 'E.T. the Extra-Terrestrial', 0),
                                                                          (106, 'Plutonium', 0),
                                                                          (106, 'Uranium', 0),
                                                                          (106, 'Flux Capacitor', 1),
                                                                          (106, 'Quantum Crystals', 0),
                                                                          (107, 'Star Trek', 1),
                                                                          (107, 'Star Wars', 0),
                                                                          (107, 'Doctor Who', 0),
                                                                          (107, 'Stargate SG-1', 0);